export const MUSIC_RESOURCE_CATEGORIES = [
  {
    id: "melody",
    label: "Melody",
    description: "Lead lines, motifs, and note-level transcription resources.",
  },
  {
    id: "chords",
    label: "Chords",
    description: "Harmony and chord progression analysis resources.",
  },
  {
    id: "song_lookup",
    label: "Song Lookup",
    description: "Song, artist, and recording discovery resources.",
  },
  {
    id: "sheet_music",
    label: "Sheet Music",
    description: "Notation, score, and engraving-oriented resources.",
  },
  {
    id: "public_domain",
    label: "Public Domain",
    description: "Public-domain notation and score sources.",
  },
  {
    id: "commercial",
    label: "Commercial",
    description: "Licensed or paid repertoire, publishing, and rights resources.",
  },
  {
    id: "synthesizer",
    label: "Synthesizer",
    description: "Sound synthesis, MIDI control, and instrument rendering.",
  },
  {
    id: "words",
    label: "Words",
    description: "Lyrics-adjacent language and vocabulary resources.",
  },
  {
    id: "vowel_sounds",
    label: "Vowel Sounds",
    description: "Phonetic resources for vowel categories and pronunciation.",
  },
  {
    id: "looping",
    label: "Looping",
    description: "Timing sync and loop playback tools.",
  },
  {
    id: "tempo",
    label: "Tempo",
    description: "Beat tracking, BPM extraction, and rhythm tools.",
  },
  {
    id: "pop_songs_and_melodies",
    label: "Pop Songs & Melodies",
    description: "Datasets and references for popular-song melodic content.",
  },
  {
    id: "music_theory",
    label: "Music Theory",
    description: "Theory references, tonal relationships, and analysis.",
  },
  {
    id: "music_practice",
    label: "Music Practice",
    description: "Practice workflows, notation playback, and educational tooling.",
  },
  {
    id: "informational_questions",
    label: "Informational Questions",
    description: "General catalog and discography lookup resources.",
  },
  {
    id: "singing_acoustics",
    label: "Singing Acoustics",
    description: "Voice analysis and acoustic measurement resources.",
  },
  {
    id: "app_usage_and_api",
    label: "App Usage & API",
    description: "Official developer docs and API usage references.",
  },
  {
    id: "formants",
    label: "Formants",
    description: "Formant estimation and vowel-formant analysis resources.",
  },
] as const;

export type MusicResourceCategory = (typeof MUSIC_RESOURCE_CATEGORIES)[number]["id"];

export const MUSIC_RESOURCE_CATEGORY_IDS = MUSIC_RESOURCE_CATEGORIES.map(
  (category) => category.id,
) as MusicResourceCategory[];

export type MusicResourceType = "api" | "dataset" | "library" | "tool" | "docs" | "reference";

export type MusicResourceLicense =
  | "public_domain"
  | "open"
  | "commercial"
  | "mixed"
  | "unknown";

export type MusicResourceCost = "free" | "freemium" | "paid" | "mixed" | "unknown";

export interface MusicResource {
  id: string;
  name: string;
  url: string;
  type: MusicResourceType;
  description: string;
  categories: readonly MusicResourceCategory[];
  tags: readonly string[];
  license: MusicResourceLicense;
  cost: MusicResourceCost;
  apiAvailable: boolean;
  requiresAuth: boolean;
  confidence: number;
  notes?: string;
}

export const MUSIC_RESOURCES: readonly MusicResource[] = [
  {
    id: "musicbrainz-api",
    name: "MusicBrainz API",
    url: "https://musicbrainz.org/doc/MusicBrainz_API",
    type: "api",
    description: "Open music metadata for artists, recordings, and releases.",
    categories: ["informational_questions", "song_lookup", "app_usage_and_api"],
    tags: ["metadata", "artist", "recording", "mbid"],
    license: "open",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.98,
  },
  {
    id: "spotify-web-api",
    name: "Spotify Web API",
    url: "https://developer.spotify.com/documentation/web-api",
    type: "api",
    description: "Catalog/search endpoints and playback-related developer APIs.",
    categories: ["informational_questions", "app_usage_and_api", "commercial"],
    tags: ["catalog", "search", "oauth", "streaming"],
    license: "commercial",
    cost: "freemium",
    apiAvailable: true,
    requiresAuth: true,
    confidence: 0.95,
    notes:
      "As of late 2024, some endpoints have tightened access for new/in-development apps.",
  },
  {
    id: "spotify-audio-analysis",
    name: "Spotify Audio Analysis Endpoint",
    url: "https://developer.spotify.com/documentation/web-api/reference/get-audio-analysis",
    type: "api",
    description: "Per-track section and timing features (tempo/key/segments), not sheet music.",
    categories: ["tempo", "melody", "app_usage_and_api", "commercial"],
    tags: ["tempo", "key", "segments", "analysis"],
    license: "commercial",
    cost: "freemium",
    apiAvailable: true,
    requiresAuth: true,
    confidence: 0.84,
  },
  {
    id: "hooktheory-api",
    name: "Hooktheory API",
    url: "https://www.hooktheory.com/api/trends/docs",
    type: "api",
    description: "Chord/harmony trends and functional progression data.",
    categories: ["chords", "music_theory", "pop_songs_and_melodies", "commercial"],
    tags: ["chords", "roman numerals", "progressions", "harmony"],
    license: "commercial",
    cost: "paid",
    apiAvailable: true,
    requiresAuth: true,
    confidence: 0.9,
  },
  {
    id: "imslp-api",
    name: "IMSLP API",
    url: "https://imslp.org/wiki/IMSLP:API",
    type: "api",
    description: "Public-domain score catalog for classical repertoire.",
    categories: ["public_domain", "sheet_music", "music_practice", "app_usage_and_api"],
    tags: ["scores", "classical", "public domain", "sheet music"],
    license: "public_domain",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.94,
  },
  {
    id: "mutopia",
    name: "Mutopia Project",
    url: "https://www.mutopiaproject.org/",
    type: "reference",
    description: "Curated public-domain and libre sheet music files.",
    categories: ["public_domain", "music_practice"],
    tags: ["sheet music", "lilypond", "midi", "public domain"],
    license: "public_domain",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.91,
  },
  {
    id: "cpdl",
    name: "CPDL (ChoralWiki)",
    url: "https://cpdl.org/wiki/",
    type: "reference",
    description: "Public-domain choral scores and texts.",
    categories: ["public_domain", "words", "music_practice"],
    tags: ["choral", "public domain", "score", "lyrics"],
    license: "public_domain",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.83,
  },
  {
    id: "basic-pitch",
    name: "Spotify Basic Pitch",
    url: "https://github.com/spotify/basic-pitch",
    type: "tool",
    description: "Open-source audio-to-MIDI transcription model for monophonic/polyphonic material.",
    categories: ["melody", "tempo", "music_practice", "singing_acoustics"],
    tags: ["transcription", "midi", "audio", "pitch"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.92,
  },
  {
    id: "basic-pitch-ts",
    name: "Basic Pitch TS",
    url: "https://github.com/spotify/basic-pitch-ts",
    type: "library",
    description: "TypeScript packaging for Basic Pitch pipelines.",
    categories: ["melody", "app_usage_and_api", "music_practice"],
    tags: ["typescript", "transcription", "midi", "browser"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.78,
  },
  {
    id: "aubio",
    name: "aubio",
    url: "https://aubio.org/",
    type: "library",
    description: "Pitch, onset, and tempo estimation library.",
    categories: ["tempo", "melody", "singing_acoustics"],
    tags: ["dsp", "pitch", "onset", "beat"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.88,
  },
  {
    id: "essentia-melody",
    name: "Essentia Melody/Pitch",
    url: "https://essentia.upf.edu/tutorial_pitch_melody.html",
    type: "docs",
    description: "Reference workflows for melody and predominant-pitch extraction.",
    categories: ["melody", "tempo", "singing_acoustics"],
    tags: ["essentia", "pitch", "melody", "audio analysis"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.86,
  },
  {
    id: "essentia-key-extractor",
    name: "Essentia KeyExtractor",
    url: "https://essentia.upf.edu/reference/std_KeyExtractor.html",
    type: "docs",
    description: "Key-detection reference for harmonic context.",
    categories: ["chords", "music_theory", "tempo"],
    tags: ["key", "harmony", "chroma", "analysis"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.82,
  },
  {
    id: "librosa",
    name: "librosa",
    url: "https://librosa.org/",
    type: "library",
    description: "Python audio analysis toolkit for beat/chroma/pitch features.",
    categories: ["tempo", "chords", "melody", "singing_acoustics"],
    tags: ["python", "beat tracking", "chroma", "dsp"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.96,
  },
  {
    id: "meyda",
    name: "Meyda",
    url: "https://meyda.js.org/",
    type: "library",
    description: "JavaScript audio feature extraction in browser or Node.",
    categories: ["tempo", "singing_acoustics", "app_usage_and_api"],
    tags: ["javascript", "audio features", "web audio", "mfcc"],
    license: "open",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.81,
  },
  {
    id: "ableton-link",
    name: "Ableton Link",
    url: "https://ableton.github.io/link/",
    type: "docs",
    description: "Network tempo synchronization protocol for jam/loop apps.",
    categories: ["looping", "tempo", "synthesizer", "music_practice"],
    tags: ["sync", "bpm", "clock", "collaboration"],
    license: "mixed",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.89,
  },
  {
    id: "linkkit",
    name: "LinkKit",
    url: "https://ableton.github.io/linkkit/",
    type: "tool",
    description: "Developer SDK/resources for integrating Ableton Link.",
    categories: ["looping", "tempo", "app_usage_and_api"],
    tags: ["sdk", "sync", "transport", "integration"],
    license: "mixed",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.78,
  },
  {
    id: "mdn-webaudio",
    name: "MDN Web Audio API",
    url: "https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API",
    type: "docs",
    description: "Core browser audio synthesis and processing reference.",
    categories: ["synthesizer", "looping", "app_usage_and_api", "music_practice"],
    tags: ["browser", "audio", "oscillator", "buffer"],
    license: "open",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.97,
  },
  {
    id: "mdn-webmidi",
    name: "MDN Web MIDI API",
    url: "https://developer.mozilla.org/docs/Web/API/Web_MIDI_API",
    type: "docs",
    description: "Browser MIDI input/output API reference.",
    categories: ["synthesizer", "music_practice", "app_usage_and_api"],
    tags: ["midi", "browser", "controllers", "synth"],
    license: "open",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.95,
  },
  {
    id: "tonejs",
    name: "Tone.js",
    url: "https://tonejs.github.io/",
    type: "library",
    description: "High-level Web Audio framework for sequencing and synths.",
    categories: ["synthesizer", "looping", "tempo", "music_practice"],
    tags: ["transport", "sequencer", "synthesis", "timing"],
    license: "open",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.95,
  },
  {
    id: "midi-2",
    name: "MIDI 2.0",
    url: "https://midi.org/midi-2-0",
    type: "reference",
    description: "Official MIDI 2.0 protocol overview and docs.",
    categories: ["synthesizer", "app_usage_and_api", "music_theory"],
    tags: ["midi", "protocol", "spec", "controllers"],
    license: "mixed",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.74,
  },
  {
    id: "flat-embed",
    name: "Flat Embed Docs",
    url: "https://flat.io/developers/docs/embed/",
    type: "docs",
    description: "Embedding notation editor/viewer for practice or playback workflows.",
    categories: ["music_practice", "app_usage_and_api", "commercial"],
    tags: ["notation", "embed", "sheet music", "ui"],
    license: "commercial",
    cost: "freemium",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.83,
  },
  {
    id: "flat-rest-api",
    name: "Flat REST API",
    url: "https://flat.io/developers/docs/api/",
    type: "api",
    description: "Programmatic score storage/import/export operations.",
    categories: ["music_practice", "app_usage_and_api", "commercial"],
    tags: ["score", "notation", "api", "import"],
    license: "commercial",
    cost: "freemium",
    apiAvailable: true,
    requiresAuth: true,
    confidence: 0.84,
  },
  {
    id: "soundslice-data-api",
    name: "Soundslice Data API",
    url: "https://www.soundslice.com/help/data-api/",
    type: "api",
    description: "Notation/tab synchronization data API (plan-dependent access).",
    categories: ["music_practice", "commercial", "app_usage_and_api", "melody", "chords"],
    tags: ["tabs", "notation", "sync", "education"],
    license: "commercial",
    cost: "paid",
    apiAvailable: true,
    requiresAuth: true,
    confidence: 0.87,
  },
  {
    id: "datamuse",
    name: "Datamuse API",
    url: "https://www.datamuse.com/api/",
    type: "api",
    description: "Word similarity/rhyme/sound queries for lyric assistance.",
    categories: ["words", "music_practice", "app_usage_and_api"],
    tags: ["rhyme", "lyrics", "vocabulary", "language"],
    license: "open",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.9,
  },
  {
    id: "cmudict",
    name: "CMU Pronouncing Dictionary",
    url: "https://github.com/cmusphinx/cmudict",
    type: "dataset",
    description: "Word pronunciations with phoneme-level ARPABET sequences.",
    categories: ["vowel_sounds", "words", "formants", "singing_acoustics"],
    tags: ["phonemes", "pronunciation", "lexicon", "arpabet"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.95,
  },
  {
    id: "praat",
    name: "Praat",
    url: "https://praat.org/",
    type: "tool",
    description: "Speech/singing acoustic analysis with pitch and formant workflows.",
    categories: ["vowel_sounds", "formants", "singing_acoustics", "music_practice"],
    tags: ["formants", "f0", "spectrogram", "phonetics"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.97,
  },
  {
    id: "parselmouth",
    name: "Parselmouth",
    url: "https://parselmouth.readthedocs.io/",
    type: "library",
    description: "Python interface to Praat for scripted acoustic analyses.",
    categories: ["formants", "singing_acoustics", "app_usage_and_api"],
    tags: ["python", "praat", "formants", "scripting"],
    license: "open",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.9,
  },
  {
    id: "opensmile",
    name: "openSMILE",
    url: "https://audeering.github.io/opensmile/",
    type: "tool",
    description: "Feature extraction toolkit for speech and singing acoustics.",
    categories: ["singing_acoustics", "formants", "tempo"],
    tags: ["features", "mfcc", "voice", "acoustics"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.88,
  },
  {
    id: "montreal-forced-aligner",
    name: "Montreal Forced Aligner",
    url: "https://montreal-forced-aligner.readthedocs.io/",
    type: "tool",
    description: "Word/phone alignment tooling useful for lyric-vowel timing.",
    categories: ["vowel_sounds", "words", "singing_acoustics", "formants"],
    tags: ["alignment", "phonemes", "timing", "transcript"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.89,
  },
  {
    id: "new-fave",
    name: "new-fave",
    url: "https://forced-alignment-and-vowel-extraction.github.io/new-fave/",
    type: "tool",
    description: "Forced alignment and automated vowel extraction pipeline.",
    categories: ["vowel_sounds", "formants", "singing_acoustics"],
    tags: ["vowel extraction", "alignment", "phonetics", "formants"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.91,
  },
  {
    id: "open-music-theory",
    name: "Open Music Theory",
    url: "https://viva.pressbooks.pub/openmusictheory/",
    type: "reference",
    description: "Comprehensive open textbook on tonal and post-tonal theory.",
    categories: ["music_theory", "informational_questions", "music_practice"],
    tags: ["theory", "intervals", "harmony", "counterpoint"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.9,
  },
  {
    id: "tonal-js",
    name: "Tonal.js",
    url: "https://github.com/tonaljs/tonal",
    type: "library",
    description: "JavaScript music theory engine for notes, scales, keys, and chords.",
    categories: ["music_theory", "chords", "app_usage_and_api", "music_practice"],
    tags: ["javascript", "scale", "chord", "key"],
    license: "open",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.95,
  },
  {
    id: "music21",
    name: "music21",
    url: "https://www.music21.org/music21docs/",
    type: "library",
    description: "Python toolkit for symbolic music analysis/generation.",
    categories: ["music_theory", "melody", "chords", "music_practice"],
    tags: ["python", "analysis", "symbolic", "musicxml"],
    license: "open",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.89,
  },
  {
    id: "musictheory-net",
    name: "musictheory.net",
    url: "https://www.musictheory.net/",
    type: "reference",
    description: "Interactive drills and concise theory explanations.",
    categories: ["music_theory", "music_practice"],
    tags: ["ear training", "theory", "exercises", "education"],
    license: "mixed",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.78,
  },
  {
    id: "discogs-api",
    name: "Discogs API",
    url: "https://www.discogs.com/developers",
    type: "api",
    description: "Release/discography metadata, labels, and catalog references.",
    categories: ["informational_questions", "app_usage_and_api", "commercial"],
    tags: ["discography", "catalog", "releases", "metadata"],
    license: "commercial",
    cost: "free",
    apiAvailable: true,
    requiresAuth: true,
    confidence: 0.88,
  },
  {
    id: "wikidata-query-service",
    name: "Wikidata Query Service",
    url: "https://query.wikidata.org/",
    type: "api",
    description: "SPARQL endpoint for factual music entity lookup.",
    categories: ["informational_questions", "app_usage_and_api"],
    tags: ["facts", "knowledge graph", "sparql", "metadata"],
    license: "open",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.8,
  },
  {
    id: "wikipedia-api",
    name: "Wikipedia (MediaWiki API)",
    url: "https://www.mediawiki.org/wiki/API:Main_page",
    type: "api",
    description: "Programmatic page lookups for background informational answers.",
    categories: ["informational_questions", "app_usage_and_api"],
    tags: ["encyclopedia", "facts", "summary", "metadata"],
    license: "open",
    cost: "free",
    apiAvailable: true,
    requiresAuth: false,
    confidence: 0.79,
  },
  {
    id: "maestro",
    name: "MAESTRO Dataset",
    url: "https://magenta.tensorflow.org/datasets/maestro",
    type: "dataset",
    description: "Aligned audio-MIDI performances, strong for melody/transcription benchmarks.",
    categories: ["pop_songs_and_melodies", "melody", "music_practice"],
    tags: ["dataset", "midi", "piano", "transcription"],
    license: "mixed",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.84,
  },
  {
    id: "million-song-dataset",
    name: "Million Song Dataset",
    url: "https://millionsongdataset.com/pages/getting-dataset/",
    type: "dataset",
    description: "Large-scale metadata and audio-feature-adjacent references for song analysis.",
    categories: ["pop_songs_and_melodies", "informational_questions", "tempo"],
    tags: ["dataset", "metadata", "features", "songs"],
    license: "mixed",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.8,
  },
  {
    id: "lakh-midi-dataset-tools",
    name: "Lakh MIDI Dataset Tooling",
    url: "https://github.com/craffel/midi-dataset",
    type: "dataset",
    description: "Tooling and metadata links for large MIDI corpora.",
    categories: ["pop_songs_and_melodies", "melody", "chords", "music_theory"],
    tags: ["midi", "dataset", "symbolic", "alignment"],
    license: "mixed",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.86,
  },
  {
    id: "openscore-lieder",
    name: "OpenScore Lieder",
    url: "https://github.com/OpenScore/Lieder",
    type: "dataset",
    description: "Open vocal score collection useful for melody/text analyses.",
    categories: ["pop_songs_and_melodies", "words", "public_domain", "formants"],
    tags: ["scores", "vocal", "dataset", "musicxml"],
    license: "open",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.75,
  },
  {
    id: "salami",
    name: "SALAMI Structural Annotations",
    url: "https://ddmal.ca/research/salami/annotation",
    type: "dataset",
    description: "Song structure annotations for section-level pop analysis.",
    categories: ["pop_songs_and_melodies", "music_theory", "informational_questions"],
    tags: ["structure", "sections", "dataset", "analysis"],
    license: "mixed",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.72,
  },
  {
    id: "openai-api-docs",
    name: "OpenAI API Docs",
    url: "https://platform.openai.com/docs",
    type: "docs",
    description: "LLM app usage, tool calling, and API integration reference.",
    categories: ["app_usage_and_api", "informational_questions"],
    tags: ["llm", "responses api", "tools", "integration"],
    license: "commercial",
    cost: "freemium",
    apiAvailable: true,
    requiresAuth: true,
    confidence: 0.97,
  },
  {
    id: "musickit",
    name: "Apple MusicKit",
    url: "https://developer.apple.com/musickit/",
    type: "docs",
    description: "Apple music app/API platform docs.",
    categories: ["app_usage_and_api", "commercial", "informational_questions"],
    tags: ["apple", "catalog", "api", "developer"],
    license: "commercial",
    cost: "freemium",
    apiAvailable: true,
    requiresAuth: true,
    confidence: 0.85,
  },
  {
    id: "youtube-data-api",
    name: "YouTube Data API",
    url: "https://developers.google.com/youtube/v3",
    type: "docs",
    description: "Video metadata/search APIs useful for informational music lookups.",
    categories: ["app_usage_and_api", "informational_questions", "commercial"],
    tags: ["search", "metadata", "video", "api"],
    license: "commercial",
    cost: "freemium",
    apiAvailable: true,
    requiresAuth: true,
    confidence: 0.77,
  },
  {
    id: "harry-fox-agency",
    name: "Harry Fox Agency",
    url: "https://www.harryfox.com/",
    type: "reference",
    description: "Licensing workflows for mechanical rights in US repertoire.",
    categories: ["commercial", "informational_questions", "words"],
    tags: ["rights", "licensing", "publishing", "mechanical"],
    license: "commercial",
    cost: "paid",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.82,
  },
  {
    id: "songfile",
    name: "Songfile",
    url: "https://www.songfile.com/",
    type: "reference",
    description: "US mechanical licensing portal for covered songs.",
    categories: ["commercial", "informational_questions"],
    tags: ["rights", "mechanical", "cover songs", "licenses"],
    license: "commercial",
    cost: "paid",
    apiAvailable: false,
    requiresAuth: true,
    confidence: 0.81,
  },
  {
    id: "sesac-repertory",
    name: "SESAC Repertory",
    url: "https://www.sesac.com/repertory/",
    type: "reference",
    description: "Performing-rights repertory lookup for songwriting credits.",
    categories: ["commercial", "informational_questions", "words"],
    tags: ["performing rights", "repertory", "credits", "publishing"],
    license: "commercial",
    cost: "free",
    apiAvailable: false,
    requiresAuth: false,
    confidence: 0.73,
  },
];
