/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    F0Selector: typeof import('./components/F0Selector.vue')['default']
    IPASelector: typeof import('./components/IPASelector.vue')['default']
    Keyboard: typeof import('./components/Keyboard.vue')['default']
    Knob: typeof import('./components/Knob.vue')['default']
    MicButton: typeof import('./components/MicButton.vue')['default']
    MidiButton: typeof import('./components/MidiButton.vue')['default']
    Readout: typeof import('./components/Readout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./components/SettingsPanel.vue')['default']
    VBtn: typeof import('./components/VBtn.vue')['default']
    VBtnToggle: typeof import('./components/VBtnToggle.vue')['default']
    VCheckbox: typeof import('./components/VCheckbox.vue')['default']
    Visualizer: typeof import('./components/Visualizer.vue')['default']
    VNum: typeof import('./components/VNum.vue')['default']
    VSelect: typeof import('./components/VSelect.vue')['default']
    VSwitch: typeof import('./components/VSwitch.vue')['default']
    VTextField: typeof import('./components/VTextField.vue')['default']
  }
}
